#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVS.API.SQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="VVSBase")]
	public partial class VVSDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertHistory(History instance);
    partial void UpdateHistory(History instance);
    partial void DeleteHistory(History instance);
    partial void InsertLines(Lines instance);
    partial void UpdateLines(Lines instance);
    partial void DeleteLines(Lines instance);
    partial void InsertVehicles(Vehicles instance);
    partial void UpdateVehicles(Vehicles instance);
    partial void DeleteVehicles(Vehicles instance);
    #endregion
		
		public VVSDatabaseDataContext() : 
				base(global::VVS.API.Properties.Settings.Default.VVSBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VVSDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VVSDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VVSDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VVSDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<History> History
		{
			get
			{
				return this.GetTable<History>();
			}
		}
		
		public System.Data.Linq.Table<Lines> Lines
		{
			get
			{
				return this.GetTable<Lines>();
			}
		}
		
		public System.Data.Linq.Table<Vehicles> Vehicles
		{
			get
			{
				return this.GetTable<Vehicles>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.History")]
	public partial class History : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _line;
		
		private int _vehicle;
		
		private int _delay;
		
		private string _direction;
		
		private string _nextstop;
		
		private System.Data.Linq.Binary _timestampt;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnlineChanging(int value);
    partial void OnlineChanged();
    partial void OnvehicleChanging(int value);
    partial void OnvehicleChanged();
    partial void OndelayChanging(int value);
    partial void OndelayChanged();
    partial void OndirectionChanging(string value);
    partial void OndirectionChanged();
    partial void OnnextstopChanging(string value);
    partial void OnnextstopChanged();
    partial void OntimestamptChanging(System.Data.Linq.Binary value);
    partial void OntimestamptChanged();
    #endregion
		
		public History()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_line", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int line
		{
			get
			{
				return this._line;
			}
			set
			{
				if ((this._line != value))
				{
					this.OnlineChanging(value);
					this.SendPropertyChanging();
					this._line = value;
					this.SendPropertyChanged("line");
					this.OnlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int vehicle
		{
			get
			{
				return this._vehicle;
			}
			set
			{
				if ((this._vehicle != value))
				{
					this.OnvehicleChanging(value);
					this.SendPropertyChanging();
					this._vehicle = value;
					this.SendPropertyChanged("vehicle");
					this.OnvehicleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delay", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int delay
		{
			get
			{
				return this._delay;
			}
			set
			{
				if ((this._delay != value))
				{
					this.OndelayChanging(value);
					this.SendPropertyChanging();
					this._delay = value;
					this.SendPropertyChanged("delay");
					this.OndelayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nextstop", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string nextstop
		{
			get
			{
				return this._nextstop;
			}
			set
			{
				if ((this._nextstop != value))
				{
					this.OnnextstopChanging(value);
					this.SendPropertyChanging();
					this._nextstop = value;
					this.SendPropertyChanged("nextstop");
					this.OnnextstopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestampt", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary timestampt
		{
			get
			{
				return this._timestampt;
			}
			set
			{
				if ((this._timestampt != value))
				{
					this.OntimestamptChanging(value);
					this.SendPropertyChanging();
					this._timestampt = value;
					this.SendPropertyChanged("timestampt");
					this.OntimestamptChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lines")]
	public partial class Lines : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private string _citycode;
		
		private System.Data.Linq.Binary _vehicle_type;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncitycodeChanging(string value);
    partial void OncitycodeChanged();
    partial void Onvehicle_typeChanging(System.Data.Linq.Binary value);
    partial void Onvehicle_typeChanged();
    #endregion
		
		public Lines()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_citycode", DbType="NChar(5)")]
		public string citycode
		{
			get
			{
				return this._citycode;
			}
			set
			{
				if ((this._citycode != value))
				{
					this.OncitycodeChanging(value);
					this.SendPropertyChanging();
					this._citycode = value;
					this.SendPropertyChanged("citycode");
					this.OncitycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle_type", DbType="Binary(1) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary vehicle_type
		{
			get
			{
				return this._vehicle_type;
			}
			set
			{
				if ((this._vehicle_type != value))
				{
					this.Onvehicle_typeChanging(value);
					this.SendPropertyChanging();
					this._vehicle_type = value;
					this.SendPropertyChanged("vehicle_type");
					this.Onvehicle_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vehicles")]
	public partial class Vehicles : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _db_id;
		
		private int _line;
		
		private System.Data.Linq.Binary _vehicle_type;
		
		private string _current_stop;
		
		private System.Nullable<int> _delay;
		
		private string _direction;
		
		private System.Nullable<bool> _isAtStop;
		
		private string _journey;
		
		private string _latitude;
		
		private string _longitude;
		
		private string _next_stop;
		
		private System.DateTimeOffset _timestamp;
		
		private System.DateTimeOffset _timestamp_before;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Ondb_idChanging(string value);
    partial void Ondb_idChanged();
    partial void OnlineChanging(int value);
    partial void OnlineChanged();
    partial void Onvehicle_typeChanging(System.Data.Linq.Binary value);
    partial void Onvehicle_typeChanged();
    partial void Oncurrent_stopChanging(string value);
    partial void Oncurrent_stopChanged();
    partial void OndelayChanging(System.Nullable<int> value);
    partial void OndelayChanged();
    partial void OndirectionChanging(string value);
    partial void OndirectionChanged();
    partial void OnisAtStopChanging(System.Nullable<bool> value);
    partial void OnisAtStopChanged();
    partial void OnjourneyChanging(string value);
    partial void OnjourneyChanged();
    partial void OnlatitudeChanging(string value);
    partial void OnlatitudeChanged();
    partial void OnlongitudeChanging(string value);
    partial void OnlongitudeChanged();
    partial void Onnext_stopChanging(string value);
    partial void Onnext_stopChanged();
    partial void OntimestampChanging(System.DateTimeOffset value);
    partial void OntimestampChanged();
    partial void Ontimestamp_beforeChanging(System.DateTimeOffset value);
    partial void Ontimestamp_beforeChanged();
    #endregion
		
		public Vehicles()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_id", DbType="NChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string db_id
		{
			get
			{
				return this._db_id;
			}
			set
			{
				if ((this._db_id != value))
				{
					this.Ondb_idChanging(value);
					this.SendPropertyChanging();
					this._db_id = value;
					this.SendPropertyChanged("db_id");
					this.Ondb_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_line", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int line
		{
			get
			{
				return this._line;
			}
			set
			{
				if ((this._line != value))
				{
					this.OnlineChanging(value);
					this.SendPropertyChanging();
					this._line = value;
					this.SendPropertyChanged("line");
					this.OnlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle_type", DbType="Binary(1) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary vehicle_type
		{
			get
			{
				return this._vehicle_type;
			}
			set
			{
				if ((this._vehicle_type != value))
				{
					this.Onvehicle_typeChanging(value);
					this.SendPropertyChanging();
					this._vehicle_type = value;
					this.SendPropertyChanged("vehicle_type");
					this.Onvehicle_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_stop", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string current_stop
		{
			get
			{
				return this._current_stop;
			}
			set
			{
				if ((this._current_stop != value))
				{
					this.Oncurrent_stopChanging(value);
					this.SendPropertyChanging();
					this._current_stop = value;
					this.SendPropertyChanged("current_stop");
					this.Oncurrent_stopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delay", DbType="Int")]
		public System.Nullable<int> delay
		{
			get
			{
				return this._delay;
			}
			set
			{
				if ((this._delay != value))
				{
					this.OndelayChanging(value);
					this.SendPropertyChanging();
					this._delay = value;
					this.SendPropertyChanged("delay");
					this.OndelayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this.OndirectionChanging(value);
					this.SendPropertyChanging();
					this._direction = value;
					this.SendPropertyChanged("direction");
					this.OndirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAtStop", DbType="Bit")]
		public System.Nullable<bool> isAtStop
		{
			get
			{
				return this._isAtStop;
			}
			set
			{
				if ((this._isAtStop != value))
				{
					this.OnisAtStopChanging(value);
					this.SendPropertyChanging();
					this._isAtStop = value;
					this.SendPropertyChanged("isAtStop");
					this.OnisAtStopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_journey", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string journey
		{
			get
			{
				return this._journey;
			}
			set
			{
				if ((this._journey != value))
				{
					this.OnjourneyChanging(value);
					this.SendPropertyChanging();
					this._journey = value;
					this.SendPropertyChanged("journey");
					this.OnjourneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_next_stop", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string next_stop
		{
			get
			{
				return this._next_stop;
			}
			set
			{
				if ((this._next_stop != value))
				{
					this.Onnext_stopChanging(value);
					this.SendPropertyChanging();
					this._next_stop = value;
					this.SendPropertyChanged("next_stop");
					this.Onnext_stopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset timestamp
		{
			get
			{
				return this._timestamp;
			}
			set
			{
				if ((this._timestamp != value))
				{
					this.OntimestampChanging(value);
					this.SendPropertyChanging();
					this._timestamp = value;
					this.SendPropertyChanged("timestamp");
					this.OntimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timestamp_before", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset timestamp_before
		{
			get
			{
				return this._timestamp_before;
			}
			set
			{
				if ((this._timestamp_before != value))
				{
					this.Ontimestamp_beforeChanging(value);
					this.SendPropertyChanging();
					this._timestamp_before = value;
					this.SendPropertyChanged("timestamp_before");
					this.Ontimestamp_beforeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
